#Saucedemo.com test constansts

base_URL = "https://www.saucedemo.com"
inventory_URL = "https://www.saucedemo.com/inventory.html"
standard_username = "standard_user"
password = "secret_sauce"
locked_username = "locked_out_user"
problem_username = "problem_user"
glitchy_username = "performance_glitch_user"
checkout_name = "Merve"
checkout_lastname = "Kasal"
checkout_zip = 20000
expected_twitter_url ="https://twitter.com/saucelabs"
expected_fb_url = "https://www.facebook.com/saucelabs"
expected_linkedin_url = "https://www.linkedin.com/company/sauce-labs/"
expexted_username_required_msg = "Epic sadface: Username is required"
expexted_password_required_msg = "Epic sadface: Password is required"
expexted_locked_user_msg = "Epic sadface: Sorry, this user has been locked out."
expected_none_user_msg = "Epic sadface: Username and password do not match any user in this service"


#LOCATORS

lgnbtn_id = "login-button"
username_id = "user-name"
password_id = "password"
username_required_msg_xpath = "/html/body/div/div/div[2]/div[1]/div/div/form/div[3]/h3"
password_required_msg_xpath = "/html/body/div/div/div[2]/div[1]/div/div/form/div[3]/h3"
locked_user_msg_xpath = "/html/body/div/div/div[2]/div[1]/div/div/form/div[3]/h3"
icon_x_selector1 = "#login_button_container > div > form > div:nth-child(1) > svg"
icon_x_selector = "#login_button_container > div > form > div:nth-child(2) > svg"
products_class_name = "inventory_item"
shop_basket_xpath = '//*[@id="shopping_cart_container"]/a'
inventory_container_id = "inventory_container"
inventory_items_class_name = "inventory_item"
inventory_items_imgs_xpath = "/html/body/div/div/div/div[2]/div/div/div/div/div[1]/a/img"
inventory_details_img_class_name = "inventory_details_img"
back_products_btn_id = "back-to-products"
burger_btn_id = "react-burger-menu-btn"
logout_btn_id = "logout_sidebar_link"
shop_cart_badge_class_name = "shopping_cart_badge"
add_cart_btns_xpath = "/html/body/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/button"
item_prices_xpath = "/html/body/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/div"
checkout_btn_id = "checkout"
checkout_name_id = "first-name"
checkout_lastname_id = "last-name"
checkout_zip_id = "postal-code"
tax_box_xpath = "/html/body/div/div/div/div[2]/div/div[2]/div[7]"
total_price_box_xpath = "/html/body/div/div/div/div[2]/div/div[2]/div[8]"
twitter_btn_xpath = "/html/body/div/div/footer/ul/li[1]/a"
fb_btn_xpath="/html/body/div/div/footer/ul/li[2]/a"
linkedin_btn_xpath = "/html/body/div/div/footer/ul/li[3]/a"
products_names_xpath = "/html/body/div/div/div/div[2]/div/div/div/div/div[2]/div[1]/a/div"
product_sort_btn_class_name = "product_sort_container"
lgn_btn_x_button = "#login_button_container > div > form > div.error-message-container.error > h3 > button"
basket_content_container_xpath = '//*[@id="shopping_cart_container"]/a'
basket_container_removedOne_class_name = "removed_cart_item"
none_user_mgs_xpath = "/html/body/div/div/div[2]/div[1]/div/div/form/div[3]/h3"
items_name_class_name = "inventory_item_name"
